"""Added Supplier and InventoryAdjustment models

Revision ID: 1197fa1a3314
Revises: e353d121e3d1
Create Date: 2026-07-24 02:12:46.338407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1197fa1a3314'
down_revision = 'e353d121e3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_adjustments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('adjustment_qty', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('qr_code_string', sa.String(length=100), nullable=True),
    sa.Column('reported_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_inventory_adjustments_department_id_departments')),
    sa.ForeignKeyConstraint(['item_id'], ['internal_products.id'], name=op.f('fk_inventory_adjustments_item_id_internal_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_adjustments'))
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_suppliers_name'), ['name'])
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('company_name')
        batch_op.drop_column('contact_name')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('whatsapp_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_suppliers_name'), type_='unique')
        batch_op.drop_column('phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('name')

    op.drop_table('inventory_adjustments')
    # ### end Alembic commands ###
