"""Add department_id to internal_products

Revision ID: 1cae1743a090
Revises: e7870ef1fc6b
Create Date: 2026-08-03 06:05:51.309984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cae1743a090'
down_revision = 'e7870ef1fc6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('subcategory', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pcs_per_scan', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_department_id_departments'), 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_department_id_departments'), type_='foreignkey')
        batch_op.drop_column('pcs_per_scan')
        batch_op.drop_column('subcategory')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
