"""Added QC Status and Inspection Log

Revision ID: 59e6869dcc9d
Revises: de55c2317a71
Create Date: 2026-07-24 01:08:55.917075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e6869dcc9d'
down_revision = 'de55c2317a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_inspection_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qr_code_string', sa.String(length=100), nullable=False),
    sa.Column('inspector_name', sa.String(length=100), nullable=False),
    sa.Column('status_given', sa.String(length=20), nullable=False),
    sa.Column('checklist_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qr_code_string'], ['qr_code_registry.qr_code_string'], name=op.f('fk_quality_inspection_logs_qr_code_string_qr_code_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_inspection_logs'))
    )
    with op.batch_alter_table('qr_code_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qc_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code_registry', schema=None) as batch_op:
        batch_op.drop_column('qc_status')

    op.drop_table('quality_inspection_logs')
    # ### end Alembic commands ###
