"""Added oem_company_code to items

Revision ID: 8f1191b328e0
Revises: 48d9bb868e95
Create Date: 2026-07-22 02:59:05.985022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1191b328e0'
down_revision = '48d9bb868e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oem_company_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('unit_of_measure', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('reorder_level', sa.Float(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('current_stock',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_internal_products_internal_code'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_internal_products_item_code'), ['item_code'])
        batch_op.drop_column('weight_grams')
        batch_op.drop_column('qr_scan_quantity')
        batch_op.drop_column('internal_code')
        batch_op.drop_column('sub_category')
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('sub_category', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('internal_code', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('qr_scan_quantity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('weight_grams', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_internal_products_item_code'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_internal_products_internal_code'), ['internal_code'])
        batch_op.alter_column('current_stock',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('reorder_level')
        batch_op.drop_column('unit_of_measure')
        batch_op.drop_column('oem_company_code')
        batch_op.drop_column('item_code')

    # ### end Alembic commands ###
