"""add price, box_qty, carton_qty to internal_products

Revision ID: a07ba5ed14b4
Revises: d752ed65a94a
Create Date: 2026-08-03 15:20:38.865621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07ba5ed14b4'
down_revision = 'd752ed65a94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('box_qty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('carton_qty', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_products', schema=None) as batch_op:
        batch_op.drop_column('carton_qty')
        batch_op.drop_column('box_qty')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
