"""Added ChallanItem model

Revision ID: a44ae178bc60
Revises: 8f1191b328e0
Create Date: 2026-07-22 15:16:28.746783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44ae178bc60'
down_revision = '8f1191b328e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challan_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('challan_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['challan_id'], ['internal_challans.id'], name=op.f('fk_challan_items_challan_id_internal_challans')),
    sa.ForeignKeyConstraint(['item_id'], ['internal_products.id'], name=op.f('fk_challan_items_item_id_internal_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challan_items'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challan_items')
    # ### end Alembic commands ###
