"""Added QRCodeRegistry table

Revision ID: de55c2317a71
Revises: a44ae178bc60
Create Date: 2026-07-23 03:14:32.287854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de55c2317a71'
down_revision = 'a44ae178bc60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_string', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('item_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('department_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Integer(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_qr_code_registry_qr_uuid'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_qr_code_registry_qr_code_string'), ['qr_code_string'])
        batch_op.drop_constraint(batch_op.f('fk_qr_code_registry_product_id_internal_products'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_qr_code_registry_challan_id_internal_challans'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_qr_code_registry_item_id_internal_products'), 'internal_products', ['item_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_qr_code_registry_department_id_departments'), 'departments', ['department_id'], ['id'])
        batch_op.drop_column('is_consumed')
        batch_op.drop_column('qr_uuid')
        batch_op.drop_column('challan_id')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('challan_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('qr_uuid', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_consumed', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_qr_code_registry_department_id_departments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_qr_code_registry_item_id_internal_products'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_qr_code_registry_challan_id_internal_challans'), 'internal_challans', ['challan_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_qr_code_registry_product_id_internal_products'), 'internal_products', ['product_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_qr_code_registry_qr_code_string'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_qr_code_registry_qr_uuid'), ['qr_uuid'])
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('department_id')
        batch_op.drop_column('item_id')
        batch_op.drop_column('qr_code_string')

    # ### end Alembic commands ###
