"""Added QC Status and Inspection Log

Revision ID: e353d121e3d1
Revises: 59e6869dcc9d
Create Date: 2026-07-24 01:51:28.559475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e353d121e3d1'
down_revision = '59e6869dcc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_clients_name'), ['name'])
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('contact_name')
        batch_op.drop_column('address')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_clients_name'), type_='unique')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
