"""Initial Supabase Postgres Setup

Revision ID: e7870ef1fc6b
Revises: 
Create Date: 2026-08-01 03:47:13.879099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7870ef1fc6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('name', name=op.f('uq_clients_name'))
    )
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('department_code', name=op.f('uq_departments_department_code')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('internal_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('oem_company_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=True),
    sa.Column('reorder_level', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internal_products')),
    sa.UniqueConstraint('item_code', name=op.f('uq_internal_products_item_code'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('name', name=op.f('uq_suppliers_name'))
    )
    op.create_table('app_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_permission_id_permissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_modules'))
    )
    op.create_table('daily_production_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('completed_quantity', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['internal_products.id'], name=op.f('fk_product_id_internal_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_production_plans'))
    )
    op.create_table('department_routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_department_id', sa.String(length=36), nullable=False),
    sa.Column('to_department_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_department_id'], ['departments.id'], name=op.f('fk_from_department_id_departments')),
    sa.ForeignKeyConstraint(['to_department_id'], ['departments.id'], name=op.f('fk_to_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department_routes')),
    sa.UniqueConstraint('from_department_id', 'to_department_id', name='uq_route_from_to')
    )
    op.create_table('department_stock',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_id_departments')),
    sa.ForeignKeyConstraint(['item_id'], ['internal_products.id'], name=op.f('fk_item_id_internal_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department_stock')),
    sa.UniqueConstraint('item_id', 'department_id', name='uq_item_department_stock')
    )
    op.create_table('dispatch_challans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('challan_number', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_challans')),
    sa.UniqueConstraint('challan_number', name=op.f('uq_dispatch_challans_challan_number'))
    )
    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('base_monthly_salary', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_table('inventory_adjustments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('adjustment_qty', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('qr_code_string', sa.String(length=100), nullable=True),
    sa.Column('reported_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_id_departments')),
    sa.ForeignKeyConstraint(['item_id'], ['internal_products.id'], name=op.f('fk_item_id_internal_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_adjustments'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('oem_company_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('internal_product_id', sa.String(length=36), nullable=False),
    sa.Column('client_product_code', sa.String(length=100), nullable=False),
    sa.Column('client_product_name', sa.String(length=255), nullable=True),
    sa.Column('box_type', sa.String(length=100), nullable=True),
    sa.Column('pieces_per_box', sa.Integer(), nullable=True),
    sa.Column('pouch_type', sa.String(length=100), nullable=True),
    sa.Column('pieces_per_pouch', sa.Integer(), nullable=True),
    sa.Column('carton_type', sa.String(length=100), nullable=True),
    sa.Column('pieces_per_carton', sa.Integer(), nullable=True),
    sa.Column('label_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_id_clients')),
    sa.ForeignKeyConstraint(['internal_product_id'], ['internal_products.id'], name=op.f('fk_internal_product_id_internal_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oem_company_codes'))
    )
    op.create_table('product_bom',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finished_good_id', sa.String(length=36), nullable=False),
    sa.Column('component_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_required', sa.Float(), nullable=False),
    sa.Column('lazer_needed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['internal_products.id'], name=op.f('fk_component_id_internal_products')),
    sa.ForeignKeyConstraint(['finished_good_id'], ['internal_products.id'], name=op.f('fk_finished_good_id_internal_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_bom'))
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('challan_number', sa.String(length=100), nullable=True),
    sa.Column('is_urgent', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('required_date', sa.DateTime(), nullable=True),
    sa.Column('edit_counter', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders'))
    )
    op.create_table('qr_code_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qr_code_string', sa.String(length=100), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('qc_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_id_departments')),
    sa.ForeignKeyConstraint(['item_id'], ['internal_products.id'], name=op.f('fk_item_id_internal_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qr_code_registry')),
    sa.UniqueConstraint('qr_code_string', name=op.f('uq_qr_code_registry_qr_code_string'))
    )
    op.create_table('recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('output_item_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['output_item_id'], ['internal_products.id'], name=op.f('fk_output_item_id_internal_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('output_item_id', name=op.f('uq_recipes_output_item_id'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('supplier_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_urgent', sa.Integer(), nullable=True),
    sa.Column('bill_image_url', sa.String(length=255), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('required_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_orders'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_id_departments')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_users_phone_number'))
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('date_string', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ot_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('employee_id', 'date_string', name='uq_employee_date')
    )
    op.create_table('dispatch_challan_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_challan_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_challan_id'], ['dispatch_challans.id'], name=op.f('fk_dispatch_challan_id_dispatch_challans')),
    sa.ForeignKeyConstraint(['item_id'], ['internal_products.id'], name=op.f('fk_item_id_internal_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_challan_items'))
    )
    op.create_table('internal_challans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('challan_number', sa.String(length=100), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=True),
    sa.Column('from_department_id', sa.String(length=36), nullable=False),
    sa.Column('to_department_id', sa.String(length=36), nullable=False),
    sa.Column('po_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('chalan_image_url', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_department_id'], ['departments.id'], name=op.f('fk_from_department_id_departments')),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_po_id_purchase_orders')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_id_suppliers')),
    sa.ForeignKeyConstraint(['to_department_id'], ['departments.id'], name=op.f('fk_to_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internal_challans')),
    sa.UniqueConstraint('challan_number', name=op.f('uq_internal_challans_challan_number'))
    )
    op.create_table('po_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('mapping_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('dispatched_qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mapping_id'], ['oem_company_codes.id'], name=op.f('fk_mapping_id_oem_company_codes')),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], name=op.f('fk_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_line_items'))
    )
    op.create_table('quality_inspection_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qr_code_string', sa.String(length=100), nullable=False),
    sa.Column('inspector_name', sa.String(length=100), nullable=False),
    sa.Column('status_given', sa.String(length=20), nullable=False),
    sa.Column('checklist_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qr_code_string'], ['qr_code_registry.qr_code_string'], name=op.f('fk_qr_code_string_qr_code_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_inspection_logs'))
    )
    op.create_table('recipe_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('input_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_required', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['input_item_id'], ['internal_products.id'], name=op.f('fk_input_item_id_internal_products')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_items'))
    )
    op.create_table('supplier_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['internal_products.id'], name=op.f('fk_product_id_internal_products')),
    sa.ForeignKeyConstraint(['supplier_order_id'], ['supplier_orders.id'], name=op.f('fk_supplier_order_id_supplier_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_order_items'))
    )
    op.create_table('challan_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('challan_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['challan_id'], ['internal_challans.id'], name=op.f('fk_challan_id_internal_challans')),
    sa.ForeignKeyConstraint(['item_id'], ['internal_products.id'], name=op.f('fk_item_id_internal_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challan_items'))
    )
    op.create_table('stock_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('challan_id', sa.String(length=36), nullable=True),
    sa.Column('qr_id', sa.String(length=36), nullable=True),
    sa.Column('is_manual', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challan_id'], ['internal_challans.id'], name=op.f('fk_challan_id_internal_challans')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_id_departments')),
    sa.ForeignKeyConstraint(['product_id'], ['internal_products.id'], name=op.f('fk_product_id_internal_products')),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_code_registry.id'], name=op.f('fk_qr_id_qr_code_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transactions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transactions')
    op.drop_table('challan_items')
    op.drop_table('supplier_order_items')
    op.drop_table('recipe_items')
    op.drop_table('quality_inspection_logs')
    op.drop_table('po_line_items')
    op.drop_table('internal_challans')
    op.drop_table('dispatch_challan_items')
    op.drop_table('attendance_records')
    op.drop_table('users')
    op.drop_table('supplier_orders')
    op.drop_table('role_permissions')
    op.drop_table('recipes')
    op.drop_table('qr_code_registry')
    op.drop_table('purchase_orders')
    op.drop_table('product_bom')
    op.drop_table('oem_company_codes')
    op.drop_table('notifications')
    op.drop_table('inventory_adjustments')
    op.drop_table('employees')
    op.drop_table('dispatch_challans')
    op.drop_table('department_stock')
    op.drop_table('department_routes')
    op.drop_table('daily_production_plans')
    op.drop_table('app_modules')
    op.drop_table('suppliers')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('internal_products')
    op.drop_table('departments')
    op.drop_table('clients')
    # ### end Alembic commands ###
